apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: madicke12/backend:v1
          imagePullPolicy: Always
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: "odc.settings"
            - name: POSTGRES_HOST
              value: "postgres"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /health/
              port: 8000
            initialDelaySeconds: 20
            periodSeconds: 5
          resources:
            requests:
              cpu:  "150m"
              memory: "128Mi"
            limits:
              cpu:  "500m"
              memory: "256Mi"
